config/routes.rb
BrickPollster::Application.routes.draw do

  root :to => "polls#index"

  match '/polls/:id/admin/:admin_token' => 'polls#show'

  resources :polls do
    resources :questions, :responses
  end

  resources :questions, :answers

  resources :responses do
    resources :answers
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :body, :owner_session_id, :question_id, :response_id

  belongs_to :response
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessible :admin_token, :public_url, :title

  validates_presence_of :title

  has_many :questions

  validates_uniqueness_of :admin_token

  before_validation :generate_admin_token

  private
    def generate_admin_token
      self.admin_token = rand(36**8).to_s(36) if self.new_record? and self.admin_token.nil?
    end

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :answer, :body, :poll

  belongs_to :poll

end

app/models/response.rb
class Response < ActiveRecord::Base
  attr_accessible :poll_id, :answers_attributes

  has_many :answers

  accepts_nested_attributes_for :answers

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
  end

  def create
  end

  def show
  end

  def destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  def index
    @polls = Poll.all
    # show list of all polls for the user
  end


  def new
    @poll = Poll.new
  end


  def create
    @poll = Poll.new(params[:poll])
    if !@poll.save
      render "new"
    else
      redirect_to "/polls/#{@poll.id}/admin/#{@poll.admin_token}"
    end
  end


  def edit
    # find the poll_id from the passed :id key (which is actually the :admin_token key)
    poll_id = params[:id]
    @poll = Poll.find_by_admin_token(poll_id)
  end


  def update
    @poll = Poll.find(params[:id])
    if !@poll.save
      render "new"
    else
      redirect_to "/polls/#{@poll.id}/admin/#{@poll.admin_token}"
    end
  end


  def show
    @poll = Poll.find(params[:id])
    if params[:admin_token]
      @admin_key = params[:admin_token]
    else
      redirect_to new_poll_response_path(@poll.id)
    end
    # this can be delineated by the url 'take_poll/'
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController


  def new
    @question = Question.new
    @poll = Poll.find(params[:poll])
  end

  def create
    @poll = Poll.find(params[:poll_id])
    @question = Question.new(params[:question])
    @question.poll_id = @poll.id
    if @question.save
      redirect_to "/polls/#{@poll.id}/admin/#{@poll.admin_token}"
    else
      render "new"
    end
  end


  def edit
    @question = Question.find(params[:id])
  end


  def update
    @question = Question.find(params[:id])
    @poll = Question.find(params[:id]).poll
    @question.body = params[:question][:body]
    if @question.save
      redirect_to "/polls/#{@poll.id}/admin/#{@poll.admin_token}"
    else
      render "new"
    end
  end


  def destroy
    @poll = Question.find(params[:id]).poll
    Question.delete(params[:id])
    redirect_to "/polls/#{@poll.id}/admin/#{@poll.admin_token}"
  end

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  def new
    @poll = Poll.find(params[:poll_id])
    @questions = @poll.questions
    @response = Response.new
  end

  def create
    response = Response.create(params[:response])
    params.each_pair do |k,v|
      Answer.create(:question_id => k.split("-")[1], :body => v, :response_id => @response_id) if k.include? "answer"
    end
    warn "IN THE CREATE of RESPONSES CONTROLLER"
  end

  def show
  end

  def destroy
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/answers/create.html.erb
<h1>Answers#create</h1>
<p>Find me in app/views/answers/create.html.erb</p>

app/views/answers/destroy.html.erb
<h1>Answers#destroy</h1>
<p>Find me in app/views/answers/destroy.html.erb</p>

app/views/answers/new.html.erb
<h1>Answers#new</h1>
<p>Find me in app/views/answers/new.html.erb</p>

app/views/answers/show.html.erb
<h1>Answers#show</h1>
<p>Find me in app/views/answers/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrickPollster</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/polls/create.html.erb
<h1>Polls#create</h1>
<p>Find me in app/views/polls/create.html.erb</p>


<p>
Private Edit URL:<br />
<%= link_to 'localhost:3000/edit/:id', edit_poll_path(@poll.id) %>
<!-- link to helper to calculate a new address! -->
</p>

<p>
Public Share URL:<br />
<%= link_to 'localhost:3000/show/:id', poll_path(@poll.id) %>
</p>

app/views/polls/edit.html.erb
<h1>Polls#edit</h1>
<p>Find me in app/views/polls/edit.html.erb</p>

<%= render 'form' %>

<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<h1>Polls#index</h1>
<p>Find me in app/views/polls/index.html.erb</p>


<%= link_to 'Create a New Poll', new_poll_path %>

<p>
  Here's the Polls already created: (for dev purposes only) <br />
<table>
  <% @polls.each_with_index do |poll, i| %>
  <tr><td> <%= i+1 %>. </td>

    <td> <%= link_to poll.title, "/polls/#{poll.id}/admin/#{poll.admin_token}" %></td>
  </tr>
<% end %>
</table>
</p>

app/views/polls/new.html.erb
<h1>Polls#new</h1>
<p>Find me in app/views/polls/new.html.erb</p>

<%= render 'form' %>


<%= link_to 'Back', polls_path %>

app/views/polls/show.html.erb
<h1>Polls#show</h1>
<p>Find me in app/views/polls/show.html.erb</p>

<!-- this shows the actual questions to the poll -->

<b><%= @poll.title %></b>

<% if @admin_key %>

<%= link_to 'Edit Title', edit_poll_path(@poll.admin_token) %>
<br />

  The poll's public URL is: <%= link_to "localhost:3000/poll/#{@poll.id}", poll_path(@poll.id) %><br />

  <p>
  <i><%= @poll.title %> Questions</i>
  </p>
  <% Question.where(:poll_id => @poll.id).each do |question|  %>
  <li> <%= question.body %>  <%= question.id %>    <!-- DELETE QUESTION ID AFTER TESTING -->
    <%= link_to 'Edit', edit_question_path(question.id) %>
    <%= link_to 'Delete', question_path(question.id), :method => :delete %><br />
    <ul> <% Answer.where(:question_id => question.id).each do |answer|  %>
      <li><%= answer.body %>
    <% end %></ul>
  <% end %>

  <p>
    <%= link_to 'Add A Question', new_question_path(:poll => @poll) %>
  </p>

<% else %>

<br />

  This is what you see if you don't have the admin key!

<% end %>

app/views/polls/update.html.erb
<h1>Polls#update</h1>
<p>Find me in app/views/polls/update.html.erb</p>

app/views/questions/_form.html.erb
<%= form_for([@poll, @question]) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :enter_question %><br />
    <%= f.text_field :body %>
  </div>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/destroy.html.erb
<h1>Questions#delete</h1>
<p>Find me in app/views/questions/delete.html.erb</p>

app/views/questions/edit.html.erb
<h1>Questions#edit</h1>
<p>Find me in app/views/questions/edit.html.erb</p>

<%= render 'form' %>

<%= link_to 'Back', polls_path %>

app/views/questions/new.html.erb
<h1>Questions#new</h1>
<p>Find me in app/views/questions/new.html.erb</p>


<b><%= @poll.title %></b>
<br />


<%= render 'form' %>

<%= link_to 'Back', polls_path %>

app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>

app/views/responses/_form.html.erb
<h1><%= @poll.title %></h1>

<%= form_for @response do |f| %>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@response.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @response.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% @questions.each_with_index do |question, i|  %>
  <%= (i+1) %>. <%=  question.body %><br />
  <%= text_field_tag "answer-#{question.id}" %> <br />
  <% end %>
  <%= f.hidden_field  :poll_id, { :value => @poll.id } %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<!-- try changing this into a poll for only @poll, with the questions being accessed individually then all the answers -->

app/views/responses/create.html.erb
<h1>Responses#create</h1>
<p>Find me in app/views/responses/create.html.erb</p>

app/views/responses/destroy.html.erb
<h1>Responses#destroy</h1>
<p>Find me in app/views/responses/destroy.html.erb</p>

app/views/responses/new.html.erb
<h1>Responses#new</h1>
<p>Find me in app/views/responses/new.html.erb</p>


<%= render 'form' %>


<%= link_to 'Back', polls_path %>

app/views/responses/show.html.erb
<h1>Responses#show</h1>
<p>Find me in app/views/responses/show.html.erb</p>